# Generated by Django 5.2 on 2025-04-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
    ]
