# Generated by Django 5.0.3 on 2025-04-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20250426_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivers',
            options={},
        ),
        migrations.AlterModelManagers(
            name='drivers',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='password',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='drivers',
            name='username',
        ),
        migrations.AlterField(
            model_name='drivers',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
